### ISSUE TITLE
Cannot access device when querying / setting dgpu

### ISSUE THREAD

**Issue by tdurand** [qzed/linux-surface-control#3]
Hi again, 

I installed the https://github.com/qzed/linux-surfacebook2-mshw0153 and I have the latest Jake patch for surface. (I have a surface book 2)

When I try:

```bash
 surface dgpu set on
```
I get

```
Error: Cannot access device.
       No such file or directory (os error 2).
```

Any pointer ? 

Thanks

**Comment by qzed** [comment]
Have you rebooted after installing the module (or alternatively loaded it via `sudo modprobe sb2_shps`)?

**Comment by tdurand** [comment]
- That was it , haven't rebooted... loading the module via your command worked

- and yes, needed sudo to set dGpu to on 

Many thanks !
